= Development Environment Setup

#TODO: intro#

== Requirements

=== System Requirements

To develop a {sw} modeler, any modern OS should suffice.

While developing, you might need to run both the backend and frontend of {sw} on your machine, so it is recommended to have at least xxx Gb of available RAM.

=== Tool Requirements

* Git
* Github account
* Java 17
* Apache Maven 3.6.3
* Docker
* Node 18.7.0
* NPM 8.15.0
* TurboRepo 

=== Know-how 

* The {sw} backend is implemented in Java/Spring. It is necessary to know Java development. Spring-specific knowledge however, is not required.
* (Optional) modelization with the https://projects.eclipse.org/projects/modeling.emf.emf[Eclipse Modeling Framework (EMF)].
* Nice-to-have: knowledge of https://eclipse.dev/sirius/[Sirius Desktop].

== Backend

#TODO: Explain how to setup the recommended devenv for the backend.#

* Essentially same as the devenv for contributors, i.e. STS + Maven + docker
* Probably also add procedure on how to clear the database to start from scratch

#TODO: which repository to clone?
For now we have to clone sirius-web and then only use a subset of it (~ sample application + our modules)
But later on we will have a blueprint we can fork.
Probably wait for the ongoing refactoring work to be completed before writing this section.#

== Frontend

#TODO: Explain how to setup the devenv for the frontend.
Essentially same as the devenv for contributors, i.e. VSCode + NPM#

To my knowledge, in the general case we do not need to contribute to the frontend when implementing a modeler, so we only need the capacities to build and run the frontend, no need for an IDE or anything like that.

Check: probably there is a way to retrieve the frontend module from NPM without even having to build it locally